/**
 * Standardized API Error Codes
 * Consistent error codes across all API endpoints for better client handling
 */

export const ERROR_CODES = {
  // Authentication & Authorization (1000-1099)
  UNAUTHORIZED: 'AUTH_1001',
  INVALID_TOKEN: 'AUTH_1002',
  TOKEN_EXPIRED: 'AUTH_1003',
  FORBIDDEN: 'AUTH_1004',
  SESSION_INVALID: 'AUTH_1005',
  CSRF_INVALID: 'AUTH_1006',
  ACCOUNT_DISABLED: 'AUTH_1007',
  EMAIL_NOT_VERIFIED: 'AUTH_1008',
  
  // Validation Errors (1100-1199)
  VALIDATION_FAILED: 'VALID_1100',
  MISSING_REQUIRED_FIELD: 'VALID_1101',
  INVALID_EMAIL: 'VALID_1102',
  INVALID_JSON: 'VALID_1110',
  INVALID_PASSWORD: 'VALID_1103',
  INVALID_FILE_TYPE: 'VALID_1104',
  FILE_TOO_LARGE: 'VALID_1105',
  INVALID_UUID: 'VALID_1106',
  INVALID_DATE_FORMAT: 'VALID_1107',
  INVALID_NUMBER: 'VALID_1108',
  INVALID_URL: 'VALID_1109',
  
  // User & Account Errors (1200-1299)
  USER_NOT_FOUND: 'USER_1201',
  USER_ALREADY_EXISTS: 'USER_1202',
  PROFILE_NOT_FOUND: 'USER_1203',
  SETTINGS_NOT_FOUND: 'USER_1204',
  ACCOUNT_SUSPENDED: 'USER_1205',
  INVALID_CREDENTIALS: 'USER_1206',
  
  // Subscription & Billing Errors (1300-1399)
  SUBSCRIPTION_NOT_FOUND: 'SUB_1301',
  SUBSCRIPTION_EXPIRED: 'SUB_1302',
  PAYMENT_REQUIRED: 'SUB_1303',
  PAYMENT_FAILED: 'SUB_1304',
  PLAN_NOT_FOUND: 'SUB_1305',
  QUOTA_EXCEEDED: 'SUB_1306',
  LIMIT_EXCEEDED: 'SUB_1307',
  BILLING_CYCLE_INVALID: 'SUB_1308',
  
  // Job & Application Errors (1400-1499)
  JOB_NOT_FOUND: 'JOB_1401',
  APPLICATION_NOT_FOUND: 'JOB_1402',
  INVALID_JOB_STATUS: 'JOB_1403',
  DUPLICATE_APPLICATION: 'JOB_1404',
  APPLICATION_CLOSED: 'JOB_1405',
  COMPANY_NOT_FOUND: 'JOB_1406',
  SPONSORSHIP_CHECK_FAILED: 'JOB_1407',
  
  // CV & Document Errors (1500-1599)
  CV_NOT_FOUND: 'CV_1501',
  CV_ANALYSIS_FAILED: 'CV_1502',
  DOCUMENT_NOT_FOUND: 'CV_1503',
  UNSUPPORTED_FILE_FORMAT: 'CV_1504',
  FILE_UPLOAD_FAILED: 'CV_1505',
  EXTRACTION_FAILED: 'CV_1506',
  
  // AI & Analysis Errors (1600-1699)
  AI_SERVICE_UNAVAILABLE: 'AI_1601',
  ANALYSIS_FAILED: 'AI_1602',
  CONTENT_GENERATION_FAILED: 'AI_1603',
  MODEL_OVERLOADED: 'AI_1604',
  INVALID_PROMPT: 'AI_1605',
  CONTENT_FILTERED: 'AI_1606',
  
  // External Service Errors (1700-1799)
  STRIPE_ERROR: 'EXT_1701',
  FIREBASE_ERROR: 'EXT_1702',
  EMAIL_SERVICE_ERROR: 'EXT_1703',
  STORAGE_ERROR: 'EXT_1704',
  THIRD_PARTY_API_ERROR: 'EXT_1705',
  RATE_LIMIT_EXCEEDED: 'EXT_1706',
  
  // Database Errors (1800-1899)
  DATABASE_CONNECTION_FAILED: 'DB_1801',
  DATABASE_QUERY_FAILED: 'DB_1802',
  DUPLICATE_RECORD: 'DB_1803',
  FOREIGN_KEY_VIOLATION: 'DB_1804',
  TRANSACTION_FAILED: 'DB_1805',
  
  // System & Infrastructure Errors (1900-1999)
  INTERNAL_SERVER_ERROR: 'SYS_1900',
  SERVICE_UNAVAILABLE: 'SYS_1901',
  TIMEOUT: 'SYS_1902',
  MAINTENANCE_MODE: 'SYS_1903',
  CONFIGURATION_ERROR: 'SYS_1904',
  
  // Network & Communication Errors (2000-2099)
  NETWORK_ERROR: 'NET_2000',
  CONNECTION_TIMEOUT: 'NET_2001',
  BAD_GATEWAY: 'NET_2002',
  GATEWAY_TIMEOUT: 'NET_2003',
  
  // Business Logic Errors (2100-2199)
  BUSINESS_RULE_VIOLATION: 'BIZ_2100',
  INVALID_OPERATION: 'BIZ_2101',
  RESOURCE_LOCKED: 'BIZ_2102',
  DEPENDENCY_MISSING: 'BIZ_2103',
  
  // Content & Data Errors (2200-2299)
  CONTENT_NOT_FOUND: 'CONTENT_2200',
  CONTENT_RESTRICTED: 'CONTENT_2201',
  DATA_CORRUPTION: 'CONTENT_2202',
  VERSION_MISMATCH: 'CONTENT_2203',
  
  // Security Errors (2300-2399)
  SUSPICIOUS_ACTIVITY: 'SEC_2300',
  BLOCKED_REQUEST: 'SEC_2301',
  MALICIOUS_REQUEST: 'SEC_2302',
  SECURITY_VIOLATION: 'SEC_2303',
} as const;

// Error code to HTTP status mapping
export const ERROR_STATUS_MAP: Record<string, number> = {
  // Authentication errors
  [ERROR_CODES.UNAUTHORIZED]: 401,
  [ERROR_CODES.INVALID_TOKEN]: 401,
  [ERROR_CODES.TOKEN_EXPIRED]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.SESSION_INVALID]: 401,
  [ERROR_CODES.CSRF_INVALID]: 403,
  [ERROR_CODES.ACCOUNT_DISABLED]: 403,
  [ERROR_CODES.EMAIL_NOT_VERIFIED]: 403,
  
  // Validation errors
  [ERROR_CODES.VALIDATION_FAILED]: 400,
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,
  [ERROR_CODES.INVALID_EMAIL]: 400,
  [ERROR_CODES.INVALID_PASSWORD]: 400,
  [ERROR_CODES.INVALID_FILE_TYPE]: 400,
  [ERROR_CODES.FILE_TOO_LARGE]: 413,
  [ERROR_CODES.INVALID_UUID]: 400,
  [ERROR_CODES.INVALID_DATE_FORMAT]: 400,
  [ERROR_CODES.INVALID_NUMBER]: 400,
  [ERROR_CODES.INVALID_URL]: 400,
  
  // User errors
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
  [ERROR_CODES.PROFILE_NOT_FOUND]: 404,
  [ERROR_CODES.SETTINGS_NOT_FOUND]: 404,
  [ERROR_CODES.ACCOUNT_SUSPENDED]: 403,
  [ERROR_CODES.INVALID_CREDENTIALS]: 401,
  
  // Subscription errors
  [ERROR_CODES.SUBSCRIPTION_NOT_FOUND]: 404,
  [ERROR_CODES.SUBSCRIPTION_EXPIRED]: 402,
  [ERROR_CODES.PAYMENT_REQUIRED]: 402,
  [ERROR_CODES.PAYMENT_FAILED]: 402,
  [ERROR_CODES.PLAN_NOT_FOUND]: 404,
  [ERROR_CODES.QUOTA_EXCEEDED]: 429,
  [ERROR_CODES.LIMIT_EXCEEDED]: 429,
  
  // Job & Application errors
  [ERROR_CODES.JOB_NOT_FOUND]: 404,
  [ERROR_CODES.APPLICATION_NOT_FOUND]: 404,
  [ERROR_CODES.INVALID_JOB_STATUS]: 400,
  [ERROR_CODES.DUPLICATE_APPLICATION]: 409,
  [ERROR_CODES.APPLICATION_CLOSED]: 410,
  [ERROR_CODES.COMPANY_NOT_FOUND]: 404,
  [ERROR_CODES.SPONSORSHIP_CHECK_FAILED]: 422,
  
  // CV & Document errors
  [ERROR_CODES.CV_NOT_FOUND]: 404,
  [ERROR_CODES.CV_ANALYSIS_FAILED]: 422,
  [ERROR_CODES.DOCUMENT_NOT_FOUND]: 404,
  [ERROR_CODES.UNSUPPORTED_FILE_FORMAT]: 415,
  [ERROR_CODES.FILE_UPLOAD_FAILED]: 422,
  [ERROR_CODES.EXTRACTION_FAILED]: 422,
  
  // AI errors
  [ERROR_CODES.AI_SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.ANALYSIS_FAILED]: 422,
  [ERROR_CODES.CONTENT_GENERATION_FAILED]: 422,
  [ERROR_CODES.MODEL_OVERLOADED]: 503,
  [ERROR_CODES.INVALID_PROMPT]: 400,
  [ERROR_CODES.CONTENT_FILTERED]: 422,
  
  // External service errors
  [ERROR_CODES.STRIPE_ERROR]: 502,
  [ERROR_CODES.FIREBASE_ERROR]: 502,
  [ERROR_CODES.EMAIL_SERVICE_ERROR]: 502,
  [ERROR_CODES.STORAGE_ERROR]: 502,
  [ERROR_CODES.THIRD_PARTY_API_ERROR]: 502,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  
  // Database errors
  [ERROR_CODES.DATABASE_CONNECTION_FAILED]: 503,
  [ERROR_CODES.DATABASE_QUERY_FAILED]: 500,
  [ERROR_CODES.DUPLICATE_RECORD]: 409,
  [ERROR_CODES.FOREIGN_KEY_VIOLATION]: 400,
  [ERROR_CODES.TRANSACTION_FAILED]: 500,
  
  // System errors
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.TIMEOUT]: 408,
  [ERROR_CODES.MAINTENANCE_MODE]: 503,
  [ERROR_CODES.CONFIGURATION_ERROR]: 500,
  
  // Network errors
  [ERROR_CODES.NETWORK_ERROR]: 503,
  [ERROR_CODES.CONNECTION_TIMEOUT]: 408,
  [ERROR_CODES.BAD_GATEWAY]: 502,
  [ERROR_CODES.GATEWAY_TIMEOUT]: 504,
  
  // Business logic errors
  [ERROR_CODES.BUSINESS_RULE_VIOLATION]: 422,
  [ERROR_CODES.INVALID_OPERATION]: 400,
  [ERROR_CODES.RESOURCE_LOCKED]: 423,
  [ERROR_CODES.DEPENDENCY_MISSING]: 424,
  
  // Content errors
  [ERROR_CODES.CONTENT_NOT_FOUND]: 404,
  [ERROR_CODES.CONTENT_RESTRICTED]: 403,
  [ERROR_CODES.DATA_CORRUPTION]: 500,
  [ERROR_CODES.VERSION_MISMATCH]: 409,
  
  // Security errors
  [ERROR_CODES.SUSPICIOUS_ACTIVITY]: 403,
  [ERROR_CODES.BLOCKED_REQUEST]: 403,
  [ERROR_CODES.MALICIOUS_REQUEST]: 400,
  [ERROR_CODES.SECURITY_VIOLATION]: 403,
};

// Default error messages for common error codes
export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.UNAUTHORIZED]: 'Authentication required',
  [ERROR_CODES.INVALID_TOKEN]: 'Invalid authentication token',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Authentication token has expired',
  [ERROR_CODES.FORBIDDEN]: 'Access denied',
  [ERROR_CODES.VALIDATION_FAILED]: 'Validation failed',
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Required field is missing',
  [ERROR_CODES.INVALID_EMAIL]: 'Invalid email address',
  [ERROR_CODES.INVALID_PASSWORD]: 'Invalid password',
  [ERROR_CODES.FILE_TOO_LARGE]: 'File size exceeds limit',
  [ERROR_CODES.USER_NOT_FOUND]: 'User not found',
  [ERROR_CODES.USER_ALREADY_EXISTS]: 'User already exists',
  [ERROR_CODES.PAYMENT_REQUIRED]: 'Payment required',
  [ERROR_CODES.JOB_NOT_FOUND]: 'Job not found',
  [ERROR_CODES.APPLICATION_NOT_FOUND]: 'Application not found',
  [ERROR_CODES.CV_NOT_FOUND]: 'CV not found',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ERROR_CODES.UNSUPPORTED_FILE_FORMAT]: 'Unsupported file format',
};
